# Generated by Django 4.1.3 on 2022-11-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questions",
            name="correct_option",
            field=models.IntegerField(),
        ),
    ]
