# Generated by Django 4.1.3 on 2022-11-18 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_questions_correct_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questions',
            old_name='difficultly',
            new_name='difficulty',
        ),
    ]
