# Generated by Django 4.1.3 on 2022-11-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_questions_title_alter_questions_chapter_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
