# Generated by Django 4.1.4 on 2023-05-08 08:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0007_alter_questions_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcceptedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=49, unique=True)),
                ("text", models.TextField(unique=True)),
                ("option_1", models.TextField()),
                ("option_2", models.TextField()),
                ("option_3", models.TextField()),
                ("option_4", models.TextField()),
                (
                    "correct_option",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(3),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Questions",
        ),
        migrations.AddField(
            model_name="acceptedquestion",
            name="question_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="question.question"
            ),
        ),
    ]
