# Generated by Django 4.1.4 on 2023-05-08 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0009_difficulty_alter_acceptedquestion_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="difficulty_level",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.difficulty",
            ),
            preserve_default=False,
        ),
    ]
