# Generated by Django 4.1.4 on 2023-05-08 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0011_questiontype_alter_question_difficulty_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="accepted",
            field=models.BooleanField(default=None, verbose_name="تایید شده"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.ForeignKey(
                default="", # type: ignore
                on_delete=django.db.models.deletion.CASCADE,
                to="question.questiontype",
                verbose_name="نوع سوال",
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="AcceptedQuestion",
        ),
    ]
