# Generated by Django 4.1.4 on 2023-05-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0012_question_accepted_question_question_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="accepted",
            field=models.BooleanField(default=False, verbose_name="تایید شده"),
        ),
    ]
