# Generated by Django 4.1.4 on 2023-05-10 11:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0013_alter_question_accepted"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisteredBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "grade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(12)],
                        verbose_name="مقطع تحصیلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب ثبت شده",
                "verbose_name_plural": "کتاب های ثبت شده",
            },
        ),
        migrations.AddField(
            model_name="difficulty",
            name="level_description",
            field=models.TextField(null=True, verbose_name="توضیحات مربوط به درجه"),
        ),
        migrations.CreateModel(
            name="RegisteredChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_name",
                    models.CharField(max_length=50, verbose_name="نام درس"),
                ),
                (
                    "chapter_number",
                    models.PositiveIntegerField(verbose_name="شماره ی درس"),
                ),
                (
                    "referenced_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="question.registeredbook",
                    ),
                ),
            ],
            options={
                "verbose_name": "درس ثبت شده",
                "verbose_name_plural": "درس های ثبت شده",
            },
        ),
        migrations.AddField(
            model_name="question",
            name="chapter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.registeredchapter",
            ),
            preserve_default=False,
        ),
    ]
