# Generated by Django 4.1.4 on 2023-05-10 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0015_alter_registeredbook_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registeredbook",
            name="grade",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MaxValueValidator(12),
                    django.core.validators.MinValueValidator(1),
                ],
                verbose_name="مقطع تحصیلی",
            ),
        ),
    ]
