# Generated by Django 4.1.4 on 2023-05-20 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0016_alter_registeredbook_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="difficulty",
            name="level_description",
            field=models.TextField(
                blank=True, default=None, verbose_name="توضیحات مربوط به درجه"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="name_level",
            field=models.CharField(max_length=20, unique=True, verbose_name="نام درجه"),
        ),
        migrations.AlterField(
            model_name="question",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="question.registeredchapter",
                verbose_name="درس",
            ),
        ),
        migrations.AlterField(
            model_name="questiontype",
            name="question_type",
            field=models.CharField(max_length=30, unique=True, verbose_name="نام نوع"),
        ),
        migrations.AlterField(
            model_name="registeredbook",
            name="name",
            field=models.CharField(max_length=50, unique=True, verbose_name="اسم"),
        ),
        migrations.AlterField(
            model_name="registeredchapter",
            name="referenced_book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="question.registeredbook",
                verbose_name="کتاب مرجع",
            ),
        ),
    ]
