# Generated by Django 4.1.4 on 2023-07-01 10:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0019_question_accepted_for_exam"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="difficulty",
            name="id",
        ),
        migrations.RemoveField(
            model_name="question",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="question",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="question",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="questiontype",
            name="id",
        ),
        migrations.RemoveField(
            model_name="registeredbook",
            name="id",
        ),
        migrations.RemoveField(
            model_name="registeredchapter",
            name="id",
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="level_name",
            field=models.CharField(
                max_length=20,
                primary_key=True,
                serialize=False,
                verbose_name="نام درجه",
            ),
        ),
        migrations.AlterField(
            model_name="questiontype",
            name="question_type",
            field=models.CharField(
                max_length=30, primary_key=True, serialize=False, verbose_name="نام نوع"
            ),
        ),
        migrations.AlterField(
            model_name="registeredbook",
            name="name",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, verbose_name="اسم"
            ),
        ),
        migrations.AlterField(
            model_name="registeredchapter",
            name="chapter_number",
            field=models.PositiveIntegerField(
                primary_key=True,
                serialize=False,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="شماره ی درس",
            ),
        ),
    ]
