# Generated by Django 4.1.4 on 2023-07-01 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0020_remove_difficulty_id_remove_question_accepted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="chapter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.registeredchapter",
                verbose_name="درس",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty_level",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.difficulty",
                verbose_name="درجه سختی",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.ForeignKey(
                default="test",
                on_delete=django.db.models.deletion.CASCADE,
                to="question.questiontype",
                verbose_name="نوع سوال",
            ),
            preserve_default=False,
        ),
    ]
