# Generated by Django 4.1.4 on 2023-07-01 17:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "question",
            "0022_alter_question_chapter_alter_question_correct_option_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="accepted_for_exam",
        ),
        migrations.RemoveField(
            model_name="question",
            name="chapter",
        ),
        migrations.RemoveField(
            model_name="question",
            name="difficulty_level",
        ),
        migrations.RemoveField(
            model_name="question",
            name="question_type",
        ),
        migrations.RemoveField(
            model_name="registeredchapter",
            name="referenced_book",
        ),
        migrations.AddField(
            model_name="difficulty",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="questiontype",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registeredbook",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registeredchapter",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="difficulty",
            name="level_name",
            field=models.CharField(max_length=20, verbose_name="نام درجه"),
        ),
        migrations.AlterField(
            model_name="questiontype",
            name="question_type",
            field=models.CharField(max_length=30, verbose_name="نام نوع"),
        ),
        migrations.AlterField(
            model_name="registeredbook",
            name="name",
            field=models.CharField(max_length=50, verbose_name="اسم"),
        ),
        migrations.AlterField(
            model_name="registeredchapter",
            name="chapter_number",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="شماره ی درس",
            ),
        ),
    ]
