# Generated by Django 4.1.4 on 2023-07-01 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0023_remove_question_accepted_for_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="accepted_for_exam",
            field=models.BooleanField(
                default=False, verbose_name="تایید شده برای آزمون"
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="chapter",
            field=models.ForeignKey(
                db_column="chapter",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.registeredchapter",
                verbose_name="درس",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="difficulty_level",
            field=models.ForeignKey(
                db_column="difficulty_level",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.difficulty",
                verbose_name="درجه سختی",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="question",
            name="question_type",
            field=models.ForeignKey(
                db_column="question_type",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.questiontype",
                verbose_name="نوع سوال",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="registeredchapter",
            name="referenced_book",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="question.registeredbook",
                verbose_name="کتاب مرجع",
            ),
            preserve_default=False,
        ),
    ]
