# Generated by Django 4.1.3 on 2022-11-29 16:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Syllabuses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("chapter_no", models.PositiveIntegerField()),
                (
                    "grade",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MaxValueValidator(12)]
                    ),
                ),
            ],
        ),
    ]
