# Generated by Django 4.1.4 on 2022-12-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="syllabuses",
            name="chapter_no",
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
