# Generated by Django 4.1.7 on 2023-07-11 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0002_alter_syllabuses_chapter_no"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Syllabuses",
        ),
    ]
