# Generated by Django 4.1.4 on 2023-07-11 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0024_question_accepted_for_exam_question_chapter_and_more"),
        ("syllabus", "0004_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Syllabuses",
            new_name="Syllabus",
        ),
    ]
