# Generated by Django 4.1.4 on 2023-07-11 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0024_question_accepted_for_exam_question_chapter_and_more"),
        ("syllabus", "0005_rename_syllabuses_syllabus"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="syllabus",
            options={"verbose_name": "جزوه", "verbose_name_plural": "جزوه ها"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "تگ", "verbose_name_plural": "تگ ها"},
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="question.registeredbook",
                verbose_name="کتاب",
            ),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="pdf_file",
            field=models.FileField(upload_to="syllabuses", verbose_name="فایل pdf"),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="tags",
            field=models.ManyToManyField(to="syllabus.tag", verbose_name="تگ ها"),
        ),
        migrations.AlterField(
            model_name="syllabus",
            name="title",
            field=models.CharField(max_length=20, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=10, verbose_name="نام"),
        ),
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        default="default.jpg", upload_to="", verbose_name="بنر"
                    ),
                ),
                (
                    "syllabus",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="syllabus.syllabus",
                        verbose_name="جزوه",
                    ),
                ),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنر ها",
            },
        ),
    ]
