# Generated by Django 4.1.4 on 2023-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0006_alter_syllabus_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="banner",
            field=models.ImageField(
                default="default.jpg", upload_to="banners", verbose_name="بنر"
            ),
        ),
    ]
