# Generated by Django 4.1.4 on 2023-07-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("syllabus", "0007_alter_banner_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="syllabus",
            name="banner",
            field=models.ImageField(
                default="default.jpg", upload_to="banners", verbose_name="بنر"
            ),
        ),
        migrations.DeleteModel(
            name="Banner",
        ),
    ]
